class_name TerrainData
extends GameData

## One act's terrain (GDD §8). Terrain sets the dominant breed and a pair of
## modifiers — one that pressures the player, one that rewards a specific
## element. That pairing is what makes the crossroad terrain choice a real
## decision rather than a difficulty slider.
##
## `id = "jungle"` -> `res://art/terrain/terrain_jungle.png`

## EnemyData id of the breed that dominates this terrain.
@export var breed_id: String = ""

## Full authored regional pools. breed_id remains the compatibility/fallback id
## used by older saves and raid reward ids.
@export var enemy_ids: Array[String] = []
@export var elite_ids: Array[String] = []

## Which act this terrain belongs to, 1-based.
@export var act: int = 1

## The boss that ends this act, by enemy id.
##
## **Here rather than in a match statement**, which is where it used to be:
## `BossDirector._expected_boss_id` mapped act to boss in code, with a comment
## saying a field "would only ever have three values". Ten acts is the version
## of that argument failing. Working rule 3 is the general form - adding a
## region is adding a file, and a region that could not name its own boss would
## have needed a code change to finish it.
@export var boss_id: String = ""

## Element that gets a bonus here, and how much. Ashfen favours Fire, Steppe
## favours Earth armour, and so on.
@export var favoured_element: TowerData.Element = TowerData.Element.FIRE

@export var favoured_element_bonus: float = 0.0

## HP per second regenerated by enemies in this terrain (Ashfen's bog-kin).
@export var enemy_hp_regen: float = 0.0

## Extra chain targets granted to Air towers (Saltglass).
@export var bonus_chain_targets: int = 0

## Multiplier on wave size and on the interval between waves (Iron Steppe:
## larger waves, shorter intervals).
@export var wave_size_multiplier: float = 1.0

@export var wave_interval_multiplier: float = 1.0

## The ground texture tiles across the whole arena, so it must be seamless.
@export var tile_size: int = 512

func get_sprite_path() -> String:
	return GameData.derive_path("terrain", "terrain_", id)
