class_name TerrainData
extends GameData

## One act's terrain (GDD §8). Terrain sets the dominant breed and a pair of
## modifiers — one that pressures the player, one that rewards a specific
## element. That pairing is what makes the crossroad terrain choice a real
## decision rather than a difficulty slider.
##
## `id = "ashfen"` -> `res://art/terrain/terrain_ashfen.png`

## EnemyData id of the breed that dominates this terrain.
@export var breed_id: String = ""

## Which act this terrain belongs to, 1-based.
@export var act: int = 1

## Element that gets a bonus here, and how much. Ashfen favours Fire, Steppe
## favours Stone armour, and so on.
@export var favoured_element: TowerData.Element = TowerData.Element.FIRE

@export var favoured_element_bonus: float = 0.0

## HP per second regenerated by enemies in this terrain (Ashfen's bog-kin).
@export var enemy_hp_regen: float = 0.0

## Extra chain targets granted to Storm towers (Saltglass).
@export var bonus_chain_targets: int = 0

## Multiplier on wave size and on the interval between waves (Iron Steppe:
## larger waves, shorter intervals).
@export var wave_size_multiplier: float = 1.0

@export var wave_interval_multiplier: float = 1.0

## The ground texture tiles across the whole arena, so it must be seamless.
@export var tile_size: int = 512


func get_sprite_path() -> String:
	return GameData.derive_path("terrain", "terrain_", id)
