class_name TerrainData
extends GameData

## One act's terrain (GDD §8). Terrain sets the dominant breed and a pair of
## modifiers — one that pressures the player, one that rewards a specific
## element. That pairing is what makes the crossroad terrain choice a real
## decision rather than a difficulty slider.
##
## `id = "jungle"` -> `res://art/terrain/terrain_jungle.png`

## EnemyData id of the breed that dominates this terrain.
@export var breed_id: String = ""

## Full authored regional pools. breed_id remains the compatibility/fallback id
## used by older saves and raid reward ids.
@export var enemy_ids: Array[String] = []
@export var elite_ids: Array[String] = []

## Which act this terrain belongs to, 1-based.
@export var act: int = 1

## Element that gets a bonus here, and how much. Ashfen favours Fire, Steppe
## favours Earth armour, and so on.
@export var favoured_element: TowerData.Element = TowerData.Element.FIRE

@export var favoured_element_bonus: float = 0.0

## HP per second regenerated by enemies in this terrain (Ashfen's bog-kin).
@export var enemy_hp_regen: float = 0.0

## Extra chain targets granted to Air towers (Saltglass).
@export var bonus_chain_targets: int = 0

## Multiplier on wave size and on the interval between waves (Iron Steppe:
## larger waves, shorter intervals).
@export var wave_size_multiplier: float = 1.0

@export var wave_interval_multiplier: float = 1.0

## The ground texture tiles across the whole arena, so it must be seamless.
@export var tile_size: int = 512

## Which of the floor's two materials covers most of the field.
##
## A region's Wang set is generated as a *lower* material with an *upper* one
## laid over it in patches, and which of the two should dominate is a fact about
## the place rather than about the tileset. The jungle set is earth-and-moss, and
## generated in that order it drew a dry terracotta field with green patches on
## it — the right two materials, in the wrong proportion, reading as scrubland.
##
## Rather than regenerate the art with the descriptions swapped, the bake flips
## the corner mask: the tile for the complement of a mask has the other material
## on exactly those corners, so `15 - mask` is the same set read the other way
## round. No new art, and one field per region says which way it is read.
@export var moss_dominant: bool = false


func get_sprite_path() -> String:
	return GameData.derive_path("terrain", "terrain_", id)
