# Puts a "Wilderhold (dev)" shortcut on the Desktop that runs the game straight
# from this working copy.
#
# Owner, 2026-09-17: "create a desktop icon so I can run the latest that the
# game is for the dev version so that I can see the latest changes easily even
# as you work ... so I dont have to keep waiting for published changes".
#
# **It runs the source, not a build.** That is the whole point: no export, no
# launcher, no release - whatever is in `game/` right now is what starts. It
# re-imports first, because Godot's runtime loads whatever `.godot/imported/`
# already holds and would otherwise draw the *previous* version of any art that
# changed since the last editor run (CLAUDE.md §4).
#
#     powershell -ExecutionPolicy Bypass -File tools\dev_shortcut.ps1
param(
    [string]$Name = "Wilderhold (dev)"
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$godotDir = Join-Path $root "Godot_v4.7.1-stable_win64.exe"
$godot = Get-ChildItem -Path $godotDir -Filter *.exe | Select-Object -First 1
if ($null -eq $godot) { throw "No Godot executable found in $godotDir" }

# A tiny launcher beside the repo rather than a shortcut straight to Godot: the
# re-import has to happen first, and a .lnk cannot run two commands.
$runner = Join-Path $root "tools\run_dev.cmd"
@"
@echo off
rem Runs Wilderhold from this working copy. Generated by tools/dev_shortcut.ps1.
cd /d "%~dp0.."
echo Importing changed assets...
"$($godot.FullName)" --headless --path game --import >nul 2>&1
git checkout -- game/project.godot 2>nul
echo Starting Wilderhold...
"$($godot.FullName)" --path game
"@ | Set-Content -Path $runner -Encoding ASCII

$desktop = [Environment]::GetFolderPath("Desktop")
$link = Join-Path $desktop "$Name.lnk"
$shell = New-Object -ComObject WScript.Shell
$shortcut = $shell.CreateShortcut($link)
$shortcut.TargetPath = $runner
$shortcut.WorkingDirectory = $root
$shortcut.Description = "Run Wilderhold from the working copy, re-importing art first"
$icon = Join-Path $root "launcher\icon.ico"
if (Test-Path $icon) { $shortcut.IconLocation = $icon }
$shortcut.Save()
Write-Output "Shortcut written to $link"
Write-Output "Runner written to $runner"
