"""Every string a translator would be handed, as a gettext template.

    python tools/extract_strings.py <out.pot>

Not a translation - there is none, and English is the only language 1.0 ships
in. This is the measure `docs/LOCALISATION.md` is built on, and the file a
translator would start from if one is ever hired: the words in the data files a
player reads, and the words the interface sets on its controls.

Godot translates a Label's or a Button's text on its own when a loaded
translation has that exact English string, so for most of the game a `.po` file
keyed by these strings is the whole job. What this cannot fix is listed in the
template's comments: a string formatted before it reaches a control, and text a
script draws itself.
"""
from __future__ import annotations

import collections
import glob
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "game")
# Fields that always hold words a player reads, even when a value is one word.
ALWAYS = {"display_name", "title", "eyebrow", "heading", "announce_title", "reading"}
# Fields that never do: identifiers, paths, sound and art names.
NEVER_SUFFIX = ("_id", "_ids", "_sfx", "_path", "_music", "_bed", "_kind", "_group")
NEVER = {"id", "image", "art", "icon", "category", "look", "species", "family", "stat",
         "anchor", "rarity", "craft", "effect", "bane_effect", "boon_effect", "portent"}
STRING_FIELD = re.compile(r'^([a-z_]+) = "((?:[^"\\]|\\.)*)"\s*$', re.M)
CONTROL_TEXT = re.compile(r'\.(text|tooltip_text|placeholder_text) = "((?:[^"\\]|\\.)*)"(.*)$')
DRAWN = re.compile(r'draw_(?:multiline_)?string\(')


def _unescape(value: str) -> str:
    return value.replace('\\"', '"').replace("\\n", "\n")


def _po(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _data_strings() -> dict:
    values = collections.defaultdict(list)
    for path in glob.glob(os.path.join(ROOT, "data", "**", "*.tres"), recursive=True):
        text = open(path, encoding="utf-8").read()
        for key, value in STRING_FIELD.findall(text):
            values[key].append((_unescape(value), os.path.relpath(path, ROOT)))
    kept = {}
    for key, entries in values.items():
        if key in NEVER or key.endswith(NEVER_SUFFIX):
            continue
        spaced = sum(1 for v, _ in entries if " " in v)
        if key in ALWAYS or spaced * 2 > len(entries):
            for value, where in entries:
                if value.strip():
                    kept.setdefault(value, []).append("%s (%s)" % (where, key))
    return kept


def _code_strings() -> tuple:
    plain, formatted, drawn = {}, {}, []
    for folder in ("scenes", "scripts", "autoload"):
        for path in glob.glob(os.path.join(ROOT, folder, "**", "*.gd"), recursive=True):
            rel = os.path.relpath(path, ROOT)
            for number, line in enumerate(open(path, encoding="utf-8"), 1):
                if line.lstrip().startswith("#"):
                    continue
                for match in CONTROL_TEXT.finditer(line):
                    value, rest = _unescape(match.group(2)), match.group(3)
                    if not re.search(r"[A-Za-z]", value):
                        continue
                    target = formatted if (rest.lstrip().startswith("%") or "%s" in value or "%d" in value) else plain
                    target.setdefault(value, []).append("%s:%d" % (rel, number))
                if DRAWN.search(line):
                    drawn.append("%s:%d" % (rel, number))
    return plain, formatted, drawn


def main() -> None:
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    data = _data_strings()
    plain, formatted, drawn = _code_strings()
    out = ['# Wilderhold - every string a translator would be handed.',
           '# Generated by tools/extract_strings.py; see docs/LOCALISATION.md.',
           'msgid ""', 'msgstr ""', '"Content-Type: text/plain; charset=UTF-8\\n"', '']
    for group, table, note in (("data", data, None), ("interface", plain, None),
                               ("formatted", formatted, "c-format: must be wrapped in tr() before formatting")):
        for value in sorted(table):
            out.append("#: " + " ".join(table[value][:4]))
            if note:
                out.append("#, " + note)
            out.append('msgid "%s"' % _po(value))
            out.append('msgstr ""')
            out.append("")
    for where in drawn:
        out.append("# drawn by a script, bypasses auto-translation: " + where)
    with open(sys.argv[1], "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    words = sum(len(v.split()) for v in data) + sum(len(v.split()) for v in plain) \
        + sum(len(v.split()) for v in formatted)
    print("data strings %d, interface strings %d, formatted %d, drawn sites %d, about %d words"
          % (len(data), len(plain), len(formatted), len(drawn), words))


if __name__ == "__main__":
    main()
