@echo off
rem Runs Wilderhold from this working copy. Generated by tools/dev_shortcut.ps1.
cd /d "%~dp0.."
echo Importing changed assets...
"E:\Arxangel\GameDev\BeastRoad\Godot_v4.7.1-stable_win64.exe\Godot_v4.7.1-stable_win64.exe" --headless --path game --import >nul 2>&1
git checkout -- game/project.godot 2>nul
echo Starting Wilderhold...
"E:\Arxangel\GameDev\BeastRoad\Godot_v4.7.1-stable_win64.exe\Godot_v4.7.1-stable_win64.exe" --path game
